// <auto-generated />
namespace Crowd.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class MultiApps5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MultiApps5));
        
        string IMigrationMetadata.Id
        {
            get { return "201507021534533_MultiApps5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
